### ISSUE TITLE
boot looping with null dereference error still present on rm when i tried to build & flash latest also still occurs in xfw even with latest changes.

### ISSUE THREAD

**Issue by jbohack** [ESurge/flipperzero-namechanger#2]
steps i did to perform however only few seem seem to get a boot loop for some reason

* start with ofw along with no apps folder
* flash rm firmware
* change name inside of the application
* reflash rm firmware again
* boot loop occurs & if it ever succeeds, a null dereference error is shown upon update instead of the update screen.

https://user-images.githubusercontent.com/37256246/211023743-06bc26e1-e32c-439a-90ac-139298915659.mov

**Comment by jbohack** [comment]
my discord is emilia#0001 if you'd like to test things

**Comment by jbohack** [comment]
if you are able to get the **update_task_is_running** from **applications/system/updater/util/update_task.h** you should be able to check for that in the **namechanger_on_system_start()** function under the namechangersrv. this way nothing gets executed while an update is running and you shouldn't need a loop because a restart occurs after a firmware flash completes.

**Comment by ESurge** [comment]
Hey, thanks for your persistence. In my testing, I didn't get a boot loop.

However, with your suggestion of using updater to halt namechanger, I've come up with a solution that should prevent this going forward (for real this time).

I'll need to write up the code and test, but I expect it should be pushed out today.

**Comment by ESurge** [comment]
So good news and bad news and more good news.

Good news is the new code works.

Bad news is I'm noticing that NameChanger isn't the source of the boot loop.

During the process of going to back stock firmware, the animations in the dolphin folder get "restored". What this restoration is doing is basically any animation that isn't part of the stock firmware gets removed, except for the folders (for some reason).

So upon checking the logs during the update process back to RM firmware, the Animation Manager tries to load up an animation from an empty folder which causes a crash.

Therefore, the fix for NameChangerSRV should also be applied to AnimationManager (technically this is within Desktop service) and hopefully that solves two boot loops.

Another piece of good news is applying the above fix to Desktop service seems to have fixed the boot loop using the test method described in this issue. The fix for NameChanger has been pushed to this repo, and the Desktop fix has been pushed to RM.

Please verify that this is working for you now (I won't close the issue so early this time!)

**Comment by jbohack** [comment]
oh jeez more than i initially expected haha! glad to see you figured it out though. boot loops & the null dereference error appear to be fixed now!

thank you, i'll be sure to let you know if i notice any more issues with it :D
